// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk-KoHuhiK2zmk2El2P-_6LyuZTGPI618',
    appId: '1:308137341906:web:7af0151117026b44aa4e0b',
    messagingSenderId: '308137341906',
    projectId: 'pernit-9ae12-hassan',
    authDomain: 'pernit-9ae12-hassan.firebaseapp.com',
    storageBucket: 'pernit-9ae12-hassan.firebasestorage.app',
    measurementId: 'G-2JN5ZNQ9SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBor1tWTLDbkM-WU1RyD52HML8NLvUQjHY',
    appId: '1:308137341906:android:da470fb6d97a32bfaa4e0b',
    messagingSenderId: '308137341906',
    projectId: 'pernit-9ae12-hassan',
    storageBucket: 'pernit-9ae12-hassan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWiJsuHLI-HSxmwKKL_bJUW3-k83ub7ic',
    appId: '1:308137341906:ios:8193c727f5187fe3aa4e0b',
    messagingSenderId: '308137341906',
    projectId: 'pernit-9ae12-hassan',
    storageBucket: 'pernit-9ae12-hassan.firebasestorage.app',
    iosBundleId: 'com.example.flutterPernit',
  );
}
